//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsociadosUI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asociados
    {
        public int Id { get; set; }
        public int Num_Asociado { get; set; }
        public string Nombre_Asociado { get; set; }
        public Nullable<int> Id_Salario { get; set; }
    }
}
