//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsociadosUI.Models.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salarios
    {
        public int Id { get; set; }
        public int Id_Salario { get; set; }
        public Nullable<int> Id_Departamento { get; set; }
        public int Anio { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
    }
}
